interface fileView {
  fileId: string,
  "fileName": string,
  "fileType": string,
  "fileUrl": string,
  "ossKey": string,
  "fileSize": string,
  "fileMd5": string,
  "vectorId": string,
  "isDeleted": number,
  "addBy": string,
  "addTime": string,
  "updatedBy": string,
  "updatedTime": string,
}